services:
  - type: web
    name: penthouse-dream-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: 8976221169:AAG5zZ6tisXvLTn4N1WKujAHQmQfVkwX9P8
      - key: RENDER_URL
        sync: false
      - key: DB_TYPE
        value: sqlite
